### ISSUE TITLE
Change download of MeilISearch in CI until fixed in MeilISearch

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch-swift#179]
**Description**
V0.21.0 makes meilisearch not downloadable and instablable with `brew`. Since our CI used brew we changed back to `curl` until it is fixed in MeiliSearch. See related: meilisearch/MeiliSearch/issues/1638

Unfortunately, by doing so we create a behavior where tests sometimes fail. See related: meilisearch/MeiliSearch/issues/908

**Solution**

Temporary solution implementation: #178

Once it is fixed in MeiliSearch, we should change the CI back to cURL.

**Comment by brunoocasali** [comment]
@bidoubiwa please correct me if I'm wrong...
The big problem I spotted here is because the script from https://install.meilisearch.com is using the GitHub API to get the latest version from Meili's release right?

The question I want to make is, this script could be used to get an arbitrary version or the only requirement is to get the latest one?
Because if the answer would be "yes, the only requirement is to load the latest", then we could remove the entire block that gets the latest version.

I made a draft PR with the idea, check it out :)

```bash
➜  meilisearch-swift git:(main) ✗ sh file.sh
Downloading MeiliSearch binary latest for macos, architecture amd64...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     16      0 --:--:-- --:--:-- --:--:--    16
MeiliSearch latest binary successfully downloaded as 'meilisearch' file.

Run it:
    $ ./meilisearch
Usage:
    $ ./meilisearch --help
```

**Comment by bidoubiwa** [comment]
Hello @brunoocasali 
Thanks for your suggestion :) I think @curquiza has a reason not to use the API route to get the latest from github. I will let her answer

**Comment by curquiza** [comment]
Sorry bruno, this issue is completely outdated, the problems described here are outdated and new one appeared, I opened an issue here: https://github.com/meilisearch/meilisearch-swift/issues/238
So I close this in favor of https://github.com/meilisearch/meilisearch-swift/issues/238
