### ISSUE TITLE
Should not ask user to jsonEncode when using the SDK

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch-swift#37]
## Problem

When using the SDK, before each call an object must be encoded in JSON. But the returned object are already decoded into the expected type. This lacks in coherence

### Exemple

In the following example I had to JSONEncode my `movie` into the `Data` type before adding it to the document parameter of `addDocuments`.
When In the second request I use the method `getOneDocument`, I recieve my movie back not as a `Movie` type and not as a `Data` type. 

It should either be Data to Data, or Swift type to Swift type.

```swift
    func testAddAndGetOneDocuments() {
        let movie: Movie = Movie(id: 10, title: "test", comment: "test movie")
        let documents: Data = try! JSONEncoder().encode([movie])

        let expectation = XCTestExpectation(description: "Add or replace Movies document")

        self.client.addDocuments(
            UID: uid,
            documents: documents,
            primaryKey: nil
        ) { result in
            switch result {
            case .success(let update):
                XCTAssertEqual(Update(updateId: 0), update)
                expectation.fulfill()
            case .failure(let error):
                XCTFail(error.localizedDescription)
            }
        }
        self.wait(for: [expectation], timeout: 1.0)
        sleep(1)
        let getExpectation = XCTestExpectation(description: "Add or replace Movies document")
        self.client.getDocument(
            UID: uid,
            identifier: "10"
        ) { (result: Result<Movie, Swift.Error>) in

            switch result {
            case .success(let returnedMovie):
                print("HELLO")
                print(returnedMovie)
                XCTAssertEqual(movie, returnedMovie)
                getExpectation.fulfill()
            case .failure(let error):
                XCTFail(error.localizedDescription)
            }
        }
        self.wait(for: [getExpectation], timeout: 3.0)
    }
```

## Solution

I prefer that the user sends its data using its specific type (in this case `Movie`). Swift will most likely be used for front end matter so while I understand that it makes it more complex to add a "big json" to meilisearch, i'm not sure any user will use swift to add documents to meilisearch (maybe i'm wrong). And in the rare cases it does, the data will come from whatever `form` the user completed and thus the data will be in a given format (i.e: Movie) and not in a jsonString.

In this case, the function prototype will look like this:

```
public func addDocuments<T>(
        UID: String,
        documents: T,
        primaryKey: String?,
        _ completion: @escaping (Result<Update, Swift.Error>) -> Void) {
        self.documents.addOrReplace(
            UID,
            documents,
            primaryKey,
            completion)
    }
```

**Comment by ppamorim** [comment]
@bidoubiwa The problem is to create a type internally that accepts `Data` and `Encodable`, I am fighting with the compiler to find a solution.

**Comment by ppamorim** [comment]
Another problem is the `JSONEncoder`, there is a problem to deal with custom date formats. I am not sure how to do this.

**Comment by ppamorim** [comment]
It was decided to keep both functions in place for the given reasons:

 - Replacing the function  `addDocuments(UID:documents:...)` with ` addDocuments<T>(UID:documents:...)` can be breaking change.
 - The function `addDocuments<T>(UID:documents:...)` forces the developer to write `Codable` objects for each data set in the application, `Codable` objects cannot be _easily_ created in runtime and the function `addDocuments(UID:documents:...)` seems to be a better alternative for data created/provided in runtime.
 - It will force developers with `objc` application to write `Codable` objects in `Swift` instead of simply using `NSJSONSerialization` already provided in `objc` that returns a `NSData` (transparent to `Data`). Knowing this, this new function `addDocuments<T>(UID:documents:...)` will be focused on Swift projects and will be recommended only for explicit types in applications.
