### ISSUE TITLE
NIO Support

### ISSUE THREAD

**Issue by kaishin** [meilisearch/meilisearch-swift#91]
I started using MeiliSearch on my server-side Swift project before I came across this repository. I made a thin NIO-based wrapper that makes it quite easy to fit any server-side project.

Taking a closer look at this repo, it seems like you've chosen to not depend on NIO, which is understandable. I was wondering if you'd be open to consider having a NIO add-on directly in this repo or in a separate one. I'd be happy to contribute my code if that's something that would interest you.

**Comment by bidoubiwa** [comment]
Hey @kaishin, 
How would an NIO add-on impact this project? Would it impact how we use this client?

**Comment by kaishin** [comment]
@bidoubiwa Depending on how it's handled, it might affect it in different ways. NIO works on Linux, Mac, iOS, and Windows, so the decision is going to be mostly about about introducing dependencies.

### Option 1: Separate NIO Package

If this is the approach chosen, the code base would benefit from being split into 2 packages:

- Domain models package (let's say `core`).
- Package sending the requests using `URLSession` (let's say `swift-urlsession`).

Following this change the new NIO package would only depend on the domain package, or `core`. The result would be 3 packages: `swift-core`, `swift-urlsession`, `swift-nio`. They can live in the same repo, or separate repos.

### Option 2: Migrate to NIO

The second option would keep the single package approach but use NIO for the requests. NIO works on all major platforms, but is fine-tuned for running on Linux and server-side environments. This means that the repository will have NIO and [async-http-client](https://github.com/swift-server/async-http-client) as dependencies.

If none of these options sound appealing to the MeiliSearch team, I am more happy to open-source my NIO package under my own account. I managed to get all endpoints working, and fixed a couple of bugs in the current one in the process.

**Comment by ppamorim** [comment]
Bonjour @kaishin 

I really like the idea of implementing NIO in the project and we are always seeking for improvements in our repository, but this requires further conversation but so far I have some questions.

 - Is it possible to use [this custom URLSession](https://github.com/meilisearch/meilisearch-swift/blob/master/Sources/MeiliSearch/Config.swift#L61) from the `Config` initializer? Since it's a protocol we could possibly create a wrapper for the HTTP layer (similar to what we have done in the unit tests), is that possible with NIO or the implementation is deeper?

 - If the question above is possible, I would prefer to keep the default `URLSession` as default in the application and create a "plugin" library that is an extension for the `Config` initializer, do you agree with me?

 - I would rather use a high-level implementation of NIO, is there any reason to not use it?

Could you please create a small sample as proof of concept and list the advantages and implications of this implementation? Be free to create draft PRs if required. :)

Regards,

**Comment by bidoubiwa** [comment]
As this issue has been stale for a long time, I'm closing it. If this still is of interest please inform us and we will re-open!

**Comment by kaishin** [comment]
@ppamorim @bidoubiwa I think it's fine to close this issue for the time being. It has been a while since I had the chance to move this discussion forward, but I have been using my own implementation in production for a little over a year now and I am happy to make it open-source as a POC. I will reach out either here or via Slack once that's done!

**Comment by bidoubiwa** [comment]
@kaishin that would be great!! 

@brunoocasali this could interest you :)
